version: '3.1'

services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "5189:5189"
    environment:
      - ASPNETCORE_URLS=http://+:5189
      - ASPNETCORE_ENVIRONMENT=Development 
    networks:
      - mynetwork

  db: #The Sql server Dockerfile is inside Database folder
    build: ./Database
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: 00PrimeraPruebaPass1197
      ACCEPT_EULA: Y
    healthcheck:
      test: [ "CMD-SHELL", "[ -x /opt/mssql-tools/bin/sqlcmd ]" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork

networks:
  mynetwork: